{% set name = "identify" %}
{% set version = "2.6.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/pre-commit/identify/archive/v{{ version }}.tar.gz
  sha256: a22c206a996684b2a29870aa4fd829b08ba1a61f3a2b68e1a3861b558a7f0517

build:
  number: 1
  script: python -m pip install . --no-deps --ignore-installed
  noarch: python
  entry_points:
    - identify-cli = identify.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - identify
  requires:
    - pytest
    - python {{ python_min }}
  source_files:
    - LICENSE
    - tests
    - setup.py
  commands:
    - identify-cli --help
    # test_license_* tests needs ukonnen which is an optional dependency
    - pytest tests -k 'not test_license'

about:
  home: https://github.com/pre-commit/identify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: File identification library for Python

extra:
  recipe-maintainers:
    - nicoddemus
    - tdegeus
    - deadsnakes-issues-bot
